Algoritmo "Real para Dollar(I)"

Var
reais, dolar, totalemdolar, totalemreais:real



Inicio
Escreval("Conversor de REAL para DÓLAR")

escreva("R$")
leia(reais)
totalemdolar<-reais/4.04
escreval("O total de R$",reais)
escreval("Será de $",totalemdolar)

escreval(" ")

Escreval("Conversor de DÓLAR para REAL")
escreva("$")
leia(dolar)
totalemreais<-dolar*4.04
escreval("O total de $",dolar)
escreval("Será de R$",totalemreais)



Fimalgoritmo